
version: '3.8'

services:
  backend_sector:
    container_name: backend_sector
    build: .
    ports:
      - 3004:3004
    environment: 
      PORT: 3004
    env_file: .env
    volumes:
      - ./:/code
      - node_modules:/code/node_modules
    networks: 
      - backend_sector
      - siged_backend
    depends_on:
      - db_sector

  db_sector:
    container_name: db_sector
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    env_file: .env
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db/.dbshell:/home/mongodb/.dbshell
      - mongodb:/data/db
    networks: 
      - backend_sector

volumes: 
  node_modules:
  mongodb:

networks: 
  backend_sector:
  siged_backend:
    external: true
